In [1]:
import pandas as pd
import numpy as np

# 1. Preprocess datasets separately

In [2]:
# Import df_crime
df_crime = pd.read_csv("../datasets/world_crime_index.csv")

# Split the City column to a City and a Country column
df_crime[['City', 'Country']] = df_crime['City'].str.split(',', expand=True).drop(2, axis=1)
df_crime["Country"] = df_crime.Country.str.lstrip()

# Get the min, max and avg crime index by country
grouped_df_crime = df_crime.groupby('Country', as_index=False)['Crime Index'].agg(["mean", "min", "max"])
grouped_df_crime.rename(columns={"mean": 'Mean Crime Index', "min": 'Min Crime Index', "max": 'Max Crime Index'}, inplace=True)
grouped_df_crime['Rank'] = grouped_df_crime['Mean Crime Index'].rank()

grouped_df_crime.sort_values(by="Rank").reset_index().head()

,Country,Mean Crime Index,Min Crime Index,Max Crime Index,Rank
0,Qatar,13.960,13.96,13.96,1.0
1,United Arab Emirates,14.825,11.67,16.30,2.0
2,Taiwan,15.050,15.05,15.05,3.0
3,Oman,20.540,20.54,20.54,4.0
4,Bahrain,21.060,21.06,21.06,5.0

In [3]:
# Import df_life
df_life = pd.read_csv("../datasets/life_expectancy_data.csv")

df_life.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [4]:
# Import happiness
df_happ_2015 = pd.read_csv("../datasets/world_hapiness/2015.csv")
df_happ_2016 = pd.read_csv("../datasets/world_hapiness/2016.csv")
df_happ_2017 = pd.read_csv("../datasets/world_hapiness/2017.csv")
df_happ_2018 = pd.read_csv("../datasets/world_hapiness/2018.csv")
df_happ_2019 = pd.read_csv("../datasets/world_hapiness/2019.csv")

# Add year column
df_happ_2015["Year"] = 2015
df_happ_2016["Year"] = 2016
df_happ_2017["Year"] = 2017
df_happ_2018["Year"] = 2018
df_happ_2019["Year"] = 2019

# Rename the dataframes
df_happ_2017.rename(columns=
                    {    
                        "Happiness.Rank": "Happiness Rank",
                        "Happiness.Score": "Happiness Score",
                        "Whisker.high": "Upper Confidence Interval",
                        "Whisker.low": "Lower Confidence Interval",
                        "Economy..GDP.per.Capita.": "Economy (GDP per Capita)",
                        "Health..Life.Expectancy.": "Health (Life Expectancy)",
                        "Trust..Government.Corruption.": "Trust (Government Corruption)",
                        "Dystopia.Residual": "Dystopia Residual"
                    }, inplace=True)

df_happ_2018.rename(columns=
                    {
                        "Overall rank": "Happiness Rank",
                        "Country or region": "Country",
                        "Score": "Happiness Score",
                        "GDP per capita": "Economy (GDP per Capita)",
                        "Healthy life expectancy": "Health (Life Expectancy)",
                        "Freedom to make life choices": "Freedom",
                        "Perceptions of corruption": "Trust (Government Corruption)"
                    }, inplace=True)

df_happ_2019.rename(columns=
                    {
                        "Overall rank": "Happiness Rank",
                        "Country or region": "Country",
                        "Score": "Happiness Score",
                        "GDP per capita": "Economy (GDP per Capita)",
                        "Healthy life expectancy": "Health (Life Expectancy)",
                        "Freedom to make life choices": "Freedom",
                        "Perceptions of corruption": "Trust (Government Corruption)"
                    }, inplace=True)

# Vertically concatenate the dataframes
df_happ = pd.concat([df_happ_2015, df_happ_2016, df_happ_2017, df_happ_2018, df_happ_2019], ignore_index=True)
df_happ.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year,Lower Confidence Interval,Upper Confidence Interval,Social support
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN,NaN

In [5]:
# Import poverty statistics
df_povstats = pd.read_csv("../datasets/povstats/PovStatsCountry.csv")
df_povstats.rename(columns={"Short Name": "Country"}, inplace=True)
df_povstats.head()

,Country Code,Country,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011",NaN,NaN,NaN,2016.0,NaN
1,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2016.0,NaN
2,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2016.0,NaN
3,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,National Institute of Statistics and Census re...,Latin America & Caribbean,Upper middle income,AR,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey, 2011/12","Integrated household survey (IHS), 2016",Yes,2008,2002.0,2016.0,NaN
4,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Lower middle income,AM,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2015",Yes,2014,NaN,2016.0,NaN

# 2. Merging datasets

In [6]:
df_combined = pd.merge(df_life, df_happ, on='Country').merge(df_povstats, on='Country').merge(grouped_df_crime.reset_index(), on='Country')

# 2.1. Preprocess numerical attributes

In [7]:
# Rename the following columns
rename_cols = {"Health (Life Expectancy)": "Factor health", 
               "Economy (GDP per Capita)": "Factor economy",
               " BMI ": "BMI",
               "Measles ": "Measles",
               " HIV/AIDS": "HIV/AIDS",
               "Life expectancy ": "Life expectancy", 
               "under-five deaths ": "under-five deaths",
               " thinness  1-19 years": "thinness 1-19 years",
               " thinness 5-9 years": "thinness 5-9 years"}

df_combined.rename(columns=rename_cols, inplace=True)

# Remove the following columns due to high factor of missing values
#  polio & diptheria have low factor missing values, but are not interesting.
to_remove_missing = ["Alcohol", "Hepatitis B", "Polio", "Total expenditure", "Standard Error", "Family", "Dystopia Residual", 
                     "Lower Confidence Interval", "Upper Confidence Interval", "Social support", "National accounts reference year", 
                     "Latest industrial data", "Unnamed: 30", "Latest industrial data", "Polio", "Diphtheria "]

df_combined.drop(to_remove_missing, inplace=True, axis=1)

# Manually supplement data for
low = {"GDP": 2,
       "Population": 1}
df_combined.loc[df_combined['Country'] == 'Egypt', 'GDP'] = 329.4
df_combined.loc[df_combined['Country'] == 'Iraq', 'GDP'] = 166.8
df_combined.loc[df_combined['Country'] == 'Egypt', 'Population'] = 97720000.0

In [8]:
# Ensure all numerical attributes are now non-negative and without NaN.
(df_combined.select_dtypes(include=[np.number]) >= 0).all()

Year_x                             True
Life expectancy                    True
Adult Mortality                    True
infant deaths                      True
percentage expenditure             True
Measles                            True
BMI                                True
under-five deaths                  True
HIV/AIDS                           True
GDP                                True
Population                         True
thinness 1-19 years                True
thinness 5-9 years                 True
Income composition of resources    True
Schooling                          True
Happiness Rank                     True
Happiness Score                    True
Factor economy                     True
Factor health                      True
Freedom                            True
Trust (Government Corruption)      True
Generosity                         True
Year_y                             True
Latest trade data                  True
Mean Crime Index                   True
Min Crime Index                    True
Max Crime Index                    True
Rank                               True
dtype: bool

# 2.2. Preprocess categorical attributes

In [9]:
# The following columns contain missing values and were deemed not interesting upon inspection. 
#  therefore, they are suitable for removal
remove_cols = ["Special Notes", "Lending category", "Other groups", "Alternative conversion factor", "PPP survey year", "Balance of Payments Manual in use", 
               "External debt Reporting status", "Government Accounting concept", "IMF data dissemination standard", "Latest household survey", 
               "Source of most recent Income and expenditure data", "Vital registration complete", "Latest agricultural census", "2-alpha code", "WB-2 code", "Region_x"]

df_combined.drop(remove_cols, inplace=True, axis=1)

In [10]:
# Ensure all categorical attributes are now without NaN
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7008 entries, 0 to 7007
Data columns (total 41 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          7008 non-null   object
 1   Year_x                           7008 non-null   int64
 2   Status                           7008 non-null   object
 3   Life expectancy                  7008 non-null   float64
 4   Adult Mortality                  7008 non-null   float64
 5   infant deaths                    7008 non-null   int64
 6   percentage expenditure           7008 non-null   float64
 7   Measles                          7008 non-null   int64
 8   BMI                              7008 non-null   float64
 9   under-five deaths                7008 non-null   int64
 10  HIV/AIDS                         7008 non-null   float64
 11  GDP                              7008 non-null   float64
 12  Population                       7008 non-null   float64
 13  thinness 1-19 years              7008 non-null   float64
 14  thinness 5-9 years               7008 non-null   float64
 15  Income composition of resources  7008 non-null   float64
 16  Schooling                        7008 non-null   float64
 17  Happiness Rank                   7008 non-null   int64
 18  Happiness Score                  7008 non-null   float64
 19  Factor economy                   7008 non-null   float64
 20  Factor health                    7008 non-null   float64
 21  Freedom                          7008 non-null   float64
 22  Trust (Government Corruption)    7008 non-null   float64
 23  Generosity                       7008 non-null   float64
 24  Year_y                           7008 non-null   int64
 25  Country Code                     7008 non-null   object
 26  Table Name                       7008 non-null   object
 27  Long Name                        7008 non-null   object
 28  Currency Unit                    7008 non-null   object
 29  Region_y                         7008 non-null   object
 30  Income Group                     7008 non-null   object
 31  National accounts base year      7008 non-null   object
 32  SNA price valuation              7008 non-null   object
 33  System of National Accounts      7008 non-null   object
 34  System of trade                  7008 non-null   object
 35  Latest population census         7008 non-null   object
 36  Latest trade data                7008 non-null   float64
 37  Mean Crime Index                 7008 non-null   float64
 38  Min Crime Index                  7008 non-null   float64
 39  Max Crime Index                  7008 non-null   float64
 40  Rank                             7008 non-null   float64
dtypes: float64(22), int64(6), object(13)
memory usage: 2.2+ MB

In [11]:
# Save the final dataset
df_combined.to_csv("../datasets/all_data.csv")